- backend/lib/tenantee_web/endpoint.ex
- backend/mix.exs
- backend/mix.lock
- frontend/.env
- frontend/package-lock.json
- frontend/src/App.tsx
> feat: add basic ui

- CONTRIBUTING.md
- README.md
> docs: contributing guide

- frontend/.editorconfig
- frontend/.eslintrc.cjs
- frontend/.prettierrc.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/main.tsx
> feat: configure eslint, editorconfig & prettier

- frontend/.eslintrc.cjs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/types/property.ts
- frontend/src/types/tenant.ts
> feat: add types for property & tenant

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.tsx
- frontend/src/components/Navigation.tsx
- frontend/src/components/Navigation/Breadcrumbs.tsx
- frontend/src/components/Navigation/Label.tsx
- frontend/src/components/PageContainer.tsx
- frontend/src/hooks/useDrawer.tsx
- frontend/src/pages/Home.tsx
> feat: setup navigation

- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.tsx
- frontend/src/components/Property/PropertyCard.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/services/api/HttpService.ts
- frontend/src/services/api/PropertyApiService.ts
- frontend/src/types/property.ts
> feat: add property listing

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.tsx
- frontend/src/components/Navigation/Navigation.tsx
- frontend/src/components/Property/Modals/AddPropertyModal.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/services/api/HttpService.ts
- frontend/src/services/api/PropertyApiService.ts
- frontend/src/types/property.ts
> feat: allow property creation from the ui

- frontend/src/components/Modals/ConfirmModal.tsx
- frontend/src/components/Property/PropertyCard.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/services/api/HttpService.ts
- frontend/src/services/api/PropertyApiService.ts
> feat: add property deletion

- .github/workflows/cypress.yml
- frontend/.gitignore
- frontend/cypress.config.ts
- frontend/cypress/component/Breadcrumbs.cy.tsx
- frontend/cypress/component/ConfirmModal.cy.tsx
- frontend/cypress/component/Label.cy.tsx
- frontend/cypress/fixtures/example.json
- frontend/cypress/support/commands.ts
- frontend/cypress/support/component-index.html
- frontend/cypress/support/component.ts
- frontend/cypress/support/e2e.ts
- frontend/cypress/tsconfig.json
- frontend/package-lock.json
- frontend/package.json
> tests: add cypress

- frontend/cypress/component/Navigation/Breadcrumbs.cy.tsx
- frontend/cypress/component/Navigation/ConfirmModal.cy.tsx
- frontend/cypress/component/Navigation/Label.cy.tsx
- frontend/src/components/Form/GenericInput.tsx
- frontend/src/components/Property/Modals/AddPropertyModal.tsx
> feat: highlight invalid input in the UI

- backend/lib/tenantee_web/controllers/property.ex
- backend/test/support/property_case.ex
> feat: allow currencies in property creation

- README.md
> docs: add instructions to readme

- frontend/src/components/Property/Modals/EditPropertyModal.tsx
- frontend/src/components/Property/PropertyCard.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/services/api/HttpService.ts
- frontend/src/services/api/PropertyApiService.ts
- frontend/src/types/property.ts
> feat: allow property update from the ui

- frontend/src/components/Tenant/Modals/EditTenantModal.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/pages/Tenants.tsx
- frontend/src/services/api/TenantApiService.ts
- frontend/src/types/tenant.ts
> Feat/allow tenant update from UI

- frontend/cypress/component/Cards/PropertyCard.cy.tsx
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/cypress/component/Modals/Property/AddPropertyModal.cy.tsx
- frontend/cypress/component/Modals/Property/EditPropertyModal.cy.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Property/Modals/AddPropertyModal.tsx
- frontend/src/components/Property/Modals/EditPropertyModal.tsx
- frontend/tsconfig.json
> feat: add currency selection in the UI

- .github/workflows/coveralls.yml
- frontend/src/pages/Property.tsx
- frontend/src/services/api/PropertyApiService.ts
> feat: add tenants to properties via ui

- backend/lib/tenantee/rent/rent.ex
- backend/lib/tenantee/rent/schema.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/controllers/tenant.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/views/property.ex
- backend/lib/tenantee_web/views/tenant.ex
- backend/priv/repo/migrations/20221119011245_switch_to_money.exs
- backend/priv/repo/migrations/20221123194029_add_rent.exs
- backend/test/support/rent_case.ex
- backend/test/tenantee_web/controllers/property_test.exs
- backend/test/tenantee_web/controllers/tenant_test.exs
> feat: add rent model into the api

- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/priv/static/swagger.json
> docs: add swagger for rent api

- backend/lib/tenantee/rent/rent.ex
- backend/lib/tenantee/rent/schema.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/controllers/rent.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/swagger/rent.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/rent.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/rent_test.exs
- backend/test/tenantee_web/views/rent_view_test.exs
> feat: allow marking rent (api)

- CHANGELOG.md
- README.md
- backend/mix.exs
- backend/priv/static/swagger.json
> docs: add changelog

- CHANGELOG.md
- CONTRIBUTING.md
- backend/lib/tenantee/rent/rent.ex
- backend/lib/tenantee_web/controllers/rent.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/rent.ex
- backend/lib/tenantee_web/views/rent.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/rent_test.exs
> feat: add rent listing to the api

- CHANGELOG.md
- backend/lib/tenantee/rent/rent.ex
- backend/lib/tenantee_web/controllers/rent.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/rent.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/rent_test.exs
> feat: add rent listing based on paid status to the api

- CHANGELOG.md
- backend/lib/tenantee/property/schema.ex
- backend/lib/tenantee/rent/worker.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/priv/repo/migrations/20221124200944_add_due_date_modifier.exs
- backend/priv/static/swagger.json
> feat: add due date modifier

- CHANGELOG.md
- backend/lib/tenantee/rent/worker.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/tenant.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/views/tenant_view_test.exs
> feat: add due rents to the tenant api response

- .env
- CHANGELOG.md
- backend/Dockerfile
- backend/run.sh
- docker-compose.yml
> feat: add docker ssl support

- CHANGELOG.md
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/types/rent.ts
- frontend/src/types/tenant.ts
> feat: add rent status to the ui

- CHANGELOG.md
- backend/lib/tenantee_web/views/tenant.ex
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/src/components/App.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/pages/Property.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/pages/Tenants.tsx
- frontend/src/services/api/RentApiService.ts
- frontend/src/services/api/TenantApiService.ts
- frontend/src/types/rent.ts
- frontend/src/types/tenant.ts
> feat: add tenant overview and rent status marking

- CHANGELOG.md
- backend/lib/tenantee/property/property.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/controllers/tenant.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/swagger/rent.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/property.ex
- backend/lib/tenantee_web/views/tenant.ex
- backend/priv/static/swagger.json
- backend/test/tenantee/rent_test.exs
- backend/test/tenantee_web/controllers/property_test.exs
- backend/test/tenantee_web/controllers/rent_test.exs
- backend/test/tenantee_web/controllers/tenant_test.exs
- backend/test/tenantee_web/views/property_view_test.exs
- backend/test/tenantee_web/views/tenant_view_test.exs
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/pages/Property.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/services/api/PropertyApiService.ts
- frontend/src/services/api/TenantApiService.ts
- frontend/src/types/property.ts
- frontend/src/types/tenant.ts
> fix: simplify swagger and responses

- CHANGELOG.md
- backend/lib/tenantee/property/property.ex
- backend/lib/tenantee/rent/rent.ex
- backend/lib/tenantee/tenant/tenant.ex
- backend/lib/tenantee/utils/currency.ex
- backend/lib/tenantee/utils/error.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/controllers/rent.ex
- backend/lib/tenantee_web/controllers/tenant.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/swagger/rent.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/error_view.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/property_test.exs
- backend/test/tenantee_web/controllers/rent_test.exs
- backend/test/tenantee_web/controllers/tenant_test.exs
> feat: better error handling

- CHANGELOG.md
- backend/lib/tenantee/preferences/preferences.ex
- backend/lib/tenantee_web/controllers/preferences.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/preferences.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/preferences_test.exs
Closes #131 
Closes #130 
Closes #129
> feat: allow setting preferences

- CHANGELOG.md
- backend/lib/tenantee/preferences/preferences.ex
- backend/lib/tenantee/utils/currency.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/views/property.ex
- backend/priv/repo/migrations/20221127230852_add_default_currency.exs
- backend/test/tenantee/preferences_test.exs
- backend/test/tenantee_web/views/property_view_test.exs
> feat: implement currency conversion

- CHANGELOG.md
- backend/lib/tenantee/stats/stats.ex
- backend/lib/tenantee/utils/currency.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/views/property.ex
- backend/priv/static/swagger.json
- backend/test/tenantee/preferences_test.exs
- backend/test/tenantee_web/controllers/property_test.exs
- backend/test/tenantee_web/views/property_view_test.exs
> feat: add monthly revenue

- backend/lib/tenantee/stats/stats.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/tenant.ex
- backend/priv/static/swagger.json
> feat: implement debt into tenant response

- CHANGELOG.md
- frontend/src/components/Property/PropertyCard.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/types/tenant.ts
> feat: Allow adding/removing tenant to a property from the tenant overview page

- CHANGELOG.md
- frontend/src/components/App.tsx
- frontend/src/pages/Home.tsx
- frontend/src/types/property.ts
> feat: turn home page into stats page

- CHANGELOG.md
- backend/lib/tenantee/property/schema.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/test/tenantee_web/controllers/property_test.exs
- frontend/cypress/component/Cards/PropertyCard.cy.tsx
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/cypress/component/Modals/Property/AddPropertyModal.cy.tsx
- frontend/cypress/component/Modals/Property/EditPropertyModal.cy.tsx
- frontend/src/components/Property/Modals/AddPropertyModal.tsx
- frontend/src/components/Property/Modals/EditPropertyModal.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/types/property.ts
> feat: alter due date modifier from the ui

- frontend/src/components/Tenant/TenantCard.tsx
> feat: implement contact icons

- CHANGELOG.md
- backend/lib/tenantee/property/schema.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/views/property.ex
- backend/priv/repo/migrations/20221129142755_add_tax_percentage.exs
- backend/priv/static/swagger.json
- backend/test/tenantee_web/views/property_view_test.exs
> feat: add tax percentage field

- CHANGELOG.md
- backend/lib/tenantee/stats/stats.ex
> feat: apply tax when calculating monthly revenue

- CHANGELOG.md
- backend/lib/tenantee_web/endpoint.ex
> fix: improper cors origins

- CHANGELOG.md
- backend/lib/tenantee/expense/expense.ex
- backend/lib/tenantee/expense/schema.ex
- backend/lib/tenantee/property/schema.ex
- backend/lib/tenantee_web/controllers/expense.ex
- backend/lib/tenantee_web/controllers/property.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/expense.ex
- backend/lib/tenantee_web/views/expense.ex
- backend/mix.exs
- backend/priv/repo/migrations/20221130050640_add_expenses.exs
- backend/priv/static/swagger.json
- backend/test/support/factory/expense.ex
- backend/test/tenantee_web/controllers/expense_test.exs
> feat: expenses API crud

- CHANGELOG.md
- backend/lib/tenantee/expense/schema.ex
- backend/lib/tenantee/property/property.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/lib/tenantee_web/views/property.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/views/property_view_test.exs
> feat: list expenses in properties

- backend/lib/tenantee/expense/expense.ex
- backend/lib/tenantee_web/controllers/expense.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/expense.ex
- backend/lib/tenantee_web/views/expense.ex
- backend/priv/static/swagger.json
- backend/test/tenantee_web/controllers/expense_test.exs
> feat: add monthly expenses

- frontend/src/hooks/useFetch.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/pages/Property.tsx
- frontend/src/pages/Settings.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/pages/Tenants.tsx
> feat: add common UI fetch hook

- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/src/components/Tenant/TenantCard.tsx
> Fix TenantCard test

- frontend/src/components/Form/GenericInput.tsx
- frontend/src/components/Property/Modals/EditPropertyModal.tsx
- frontend/src/components/Tenant/Modals/EditTenantModal.tsx
> Fix warnings

- frontend/src/components/Form/CurrencySelect.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/Property.tsx
- frontend/src/utils/money.ts
> Format money properly

- frontend/cypress/component/Modals/Property/AddPropertyModal.cy.tsx
- frontend/cypress/component/Modals/Property/EditPropertyModal.cy.tsx
- frontend/src/components/Property/Modals/AddPropertyModal.tsx
- frontend/src/components/Property/Modals/EditPropertyModal.tsx
- frontend/src/types/property.ts
> feat: Add tax percentage in the UI

- backend/lib/tenantee/stats/stats.ex
- backend/lib/tenantee_web/swagger/property.ex
- backend/priv/static/swagger.json
- backend/test/support/factory/property.ex
- backend/test/tenantee_web/controllers/property_test.exs
> fix: fix tax calculation

- CHANGELOG.md
- backend/lib/tenantee/property/schema.ex
- backend/lib/tenantee/tenant/communication/schema.ex
- backend/lib/tenantee/tenant/schema.ex
- backend/lib/tenantee/tenant/tenant.ex
- backend/lib/tenantee_web/controllers/tenant.ex
- backend/lib/tenantee_web/router.ex
- backend/lib/tenantee_web/swagger/tenant.ex
- backend/lib/tenantee_web/views/communication.ex
- backend/lib/tenantee_web/views/tenant.ex
- backend/priv/repo/migrations/20230215011200_add_communication.exs
- backend/priv/repo/migrations/20230215012247_remove_phone_and_email.exs
- backend/priv/static/swagger.json
- backend/test/support/factory/communication.ex
- backend/test/support/factory/tenant.ex
- backend/test/tenantee_web/controllers/property_test.exs
- backend/test/tenantee_web/controllers/tenant_test.exs
- backend/test/tenantee_web/views/communication_view_test.exs
- backend/test/tenantee_web/views/tenant_view_test.exs
> feat: add social channels to the api

- CHANGELOG.md
- backend/lib/tenantee/tenant/tenant.ex
- frontend/src/components/Form/GenericInput.tsx
- frontend/src/components/Tenant/Modals/AddTenantModal.tsx
- frontend/src/components/Tenant/Modals/EditTenantModal.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/components/Tenant/TenantCommunicationList.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/services/api/TenantApiService.ts
- frontend/src/types/tenant.ts
> Allow manipulation of communication channels from the UI

- CHANGELOG.md
- frontend/cypress/component/Cards/TenantCard.cy.tsx
- frontend/cypress/component/Navigation/ConfirmModal.cy.tsx
- frontend/src/components/Modals/BaseModal.tsx
- frontend/src/components/Modals/ConfirmModal.tsx
- frontend/src/components/Tenant/TenantCard.tsx
- frontend/src/components/Tenant/TenantCommunicationList.tsx
- frontend/src/pages/Properties.tsx
- frontend/src/pages/Property.tsx
- frontend/src/pages/Tenant.tsx
- frontend/src/pages/Tenants.tsx
> feat: communication channels modal

- frontend/src/components/Tenant/TenantCommunicationList.tsx
> feat: if communication is supported, make a link instead of text

- frontend/cypress/component/Cards/PropertyCard.cy.tsx
- frontend/cypress/component/Modals/Property/EditPropertyModal.cy.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Property.tsx
- frontend/src/types/property.ts
> feat: add profit/loss chart on property page

- backend/Dockerfile
> fix: add missing command to Dockerfile

- .gitignore
- Dockerfile
- assets/package-lock.json
- assets/package.json
- config/prod.exs
- docker-compose.yml
- lib/tenantee_web/live/config_live.ex
- run.sh
> Optimize Docker

- test/live/property/list_test.exs
- test/live/tenant/list_test.exs
> TEST: Add missing tests

- lib/tenantee_web/controllers/error_html.ex
- lib/tenantee_web/controllers/error_html/404.html.heex
- lib/tenantee_web/controllers/error_html/500.html.heex
> fix: fix add default error pages

- assets/js/hooks/form.js
- lib/tenantee/entity/communication_channel.ex
- lib/tenantee/entity/tenant.ex
- lib/tenantee/schema/communication_channel.ex
- lib/tenantee/schema/tenant.ex
- lib/tenantee_web/live/property_live/add.ex
- lib/tenantee_web/live/property_live/edit.ex
- lib/tenantee_web/live/tenant_live/edit.ex
- lib/tenantee_web/live/tenant_live/helper.ex
- priv/repo/migrations/20230619214008_add_communication_channels.exs
- test/data/communication_channels_test.exs
- test/data/tenant_test.exs
- test/live/property/list_test.exs
- test/live/tenant/edit_test.exs
- test/live/tenant/list_test.exs
- test/support/factory/communication_channels.ex
Closes #400 
While this does add communication channels functionality, we still need more styling, better display, etc.
That can be added in later though.
> feat: add communication channels

- .github/workflows/check.yml
- CHANGELOG.md
- lib/tenantee/cldr.ex
- lib/tenantee/config.ex
- lib/tenantee/entity/property.ex
- lib/tenantee/entity/rent.ex
- lib/tenantee_web/components/property.ex
- lib/tenantee_web/live/config_live.ex
- lib/tenantee_web/live/home_live.ex
- priv/repo/migrations/20230622205937_add_postgres_money_sum_function.exs
- test/data/rent_test.exs
- test/live/home_test.exs
- test/test_helper.exs
> feat: add tax

- lib/tenantee/cldr.ex
- lib/tenantee_web/components/tenant.ex
- lib/tenantee_web/live/home_live.ex
- test/other/cldr_test.exs
> feat: add pluralize function
